version: "3.0"
services:
  database:
    image: amsterdam/postgres11
    ports:
      - "5442:5432"
    environment:
      POSTGRES_DB: overlastgebieden
      POSTGRES_USER: overlastgebieden
      POSTGRES_PASSWORD: insecure
      LOCAL: "True"
    extra_hosts:
      admin.datapunt.amsterdam.nl: 10.99.157.24
    volumes:
        - "~/.ssh/datapunt.key:/root/.ssh/datapunt.key"

  importer:
    image: repo.data.amsterdam.nl/datapunt/overlastgebieden:${ENVIRONMENT}
    links:
      - database
    environment:
      BAG_BRK_OBJECTSTORE_PASSWORD: ${BAG_BRK_OBJECTSTORE_PASSWORD}
      DATABASE_NAME: overlastgebieden
      DATABASE_USER: overlastgebieden
      DATABASE_PASSWORD: insecure
      DATABASE_HOST_OVERRIDE: database
      DATABASE_PORT_OVERRIDE: 5432
      ENVIRONMENT:
    command: make runimport

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    links:
      - database
    environment:
      BAG_BRK_OBJECTSTORE_PASSWORD: ${BAG_BRK_OBJECTSTORE_PASSWORD}
      DATABASE_NAME: overlastgebieden
      DATABASE_USER: overlastgebieden
      DATABASE_PASSWORD: insecure
      DATABASE_HOST_OVERRIDE: database
      DATABASE_PORT_OVERRIDE: 5432

  db-backup:
    image: amsterdam/postgres11
    links:
      - database:db
    volumes:
      - ./backups:/tmp/backups
    command: >
      bash -c "echo db:5432:overlastgebieden:overlastgebieden:insecure > ~/.pgpass \
              && chmod 600 ~/.pgpass \
              && pg_dump  -Fc \
                          -U overlastgebieden \
                          -h db -p 5432 \
                          overlastgebieden > /tmp/backups/database.dump"
